language: generic

# Para poder hacer uso de docker se necesita root permission por ello el sudo
sudo: required

# Con esto se le indica a TRAVIS CI que se necesita docker  
services:
  -docker

# Setup necesario para antes de que se ejecuten los tests
before_install:
  # Este tag establecido puede ser cualquiera ya que solo se usa aqui pero es bueno seguir las convenciones
  - docker build -t gtorres777/docker-react -f Dockerfile.dev .

# Serie de comandos a ejecutarse
script:
  # El CI como ture hace que al correr los test de react, ya no
  # aparezca lo que aparece como cuando se ejecuta el watch
  - docker run -e CI=true gtorres777/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-111355452311"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
